name: teste-php-techsocial
recipe: lamp
config:
  webroot: public
  php: 8.2
  database: postgres
  xdebug: true
  config:
    php: scripts/php.ini

services:
  appserver:
    overrides:
      extra_hosts:
        - "host.docker.internal:host-gateway"
  testdb:
    type: postgres
    portforward: 6666

tooling:
  migrate:
    service: appserver
    cmd:
      - "vendor/bin/phinx migrate"
  create-migration:
    service: appserver
    cmd:
      - "vendor/bin/phinx create "
  pest-init:
    service: appserver
    cmd:
      - "vendor/bin/pest --init"
  run-tests:
    service: appserver
    cmd:
      - "vendor/bin/pest"